### ISSUE TITLE
Crear clase para Inicio Sesion

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/Proyecto_Ufi-G2#12]
Crear clase con atributos establecidos hasta el momento.

**Comment by GaboMG6** [comment]
La tarea ya la hice,la subo mas tarde.Gracias.

**Comment by electromilitary45** [comment]
Fecha: 7/7/2022 || Hora : 23:50 pm
La tarea se reabre y se mantiene en estado de revision ya que todavia no se entrega ni crea el commit respectivo como la arcodado. Una semana tarde.

**Comment by electromilitary45** [comment]
Tarea no entregada por @GaboMG6............. 
Me encargado yo de eso

@sblanco20141
