### ISSUE TITLE
Creacion de Documento de Requerimientos

### ISSUE THREAD

**Issue by electromilitary45** [electromilitary45/Proyecto_Ufi-G2#7]

**Comment by electromilitary45** [comment]
INICIAR EL DOCUMENTO 
WORD COLABORATIVO: https://ufidelitas-my.sharepoint.com/:w:/g/personal/dleiva00042_ufide_ac_cr/ERcVlhqciQ1KlEqE-26YB-MBCNsg-RhAxt_vcDAtcoKq2Q?e=SEToDm

**Comment by nmadrigal60360** [comment]
Agrego datos al documento de requerimientos, este documento no esta completo.

**Comment by electromilitary45** [comment]
Excelente, Muchas gracias
